title: Connect an LED to the Raspberry Pi
hero_image: images/banner.png
description: Connecting an LED to the Raspberry Pi
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - title: Connectan LED to the Raspberry Pi
