---
title: Ligar um LED ao Raspberry Pi
hero_image: images/banner.png
description: Ligar um LED ao Raspberry Pi
theme: vermelho #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies:
site_areas:
steps:
  - 
    title: Ligar um LED ao Raspberry Pi
