---
title: Anschließen einer LED an einen Raspberry Pi
hero_image: images/banner.png
description: Eine LED an einen Raspberry Pi anschließen
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies:
site_areas:
steps:
  - title: Anschließen einer LED an einen Raspberry Pi
